[rospy.client][INFO] 2017-10-18 07:48:29,769: init_node, name[/state_follow_waypoint], pid[30809]
[xmlrpc][INFO] 2017-10-18 07:48:29,771: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:48:29,778: ROS Slave URI: [http://10.0.0.116:39812/]
[xmlrpc][INFO] 2017-10-18 07:48:29,779: Started XML-RPC server [http://10.0.0.116:39812/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:48:29,779: _ready: http://10.0.0.116:39812/
[xmlrpc][INFO] 2017-10-18 07:48:29,780: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:48:29,783: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:48:29,879: registered with master
[rospy.rosout][INFO] 2017-10-18 07:48:29,880: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:48:29,913: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:48:29,928: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:48:30,114: topic[/state_command] adding connection to [http://10.0.0.116:43297/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:30,118: topic[/state_command] adding connection to [http://10.0.0.116:35502/], count 1
[rospy.internal][INFO] 2017-10-18 07:48:30,128: topic[/state_command] adding connection to [http://10.0.0.116:39812/], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,143: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:48:30,167: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:48:30,175: topic[/state_command] adding connection to [http://10.0.0.116:41980/], count 3
[rospy.internal][INFO] 2017-10-18 07:48:30,188: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,211: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:48:30,265: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:48:31,281: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,351: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,353: topic[/mavros/state] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,483: topic[/mavros/battery] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,484: topic[/mavlink/from] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,884: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,988: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,012: topic[/state_command] adding connection to [http://10.0.0.116:38610/], count 4
[rospy.internal][INFO] 2017-10-18 07:48:32,130: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:48:43,466: /state_follow_waypoint MsgId 46 detected. WP item # 7936
[rospy.core][INFO] 2017-10-18 07:48:59,861: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:49:00,044: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:49:00,044: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:49:00,045: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:49:00,046: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:49:00,047: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:49:00,048: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:49:00,049: topic[/exec_command] removing connection to /exec
[rospy.internal][ERROR] 2017-10-18 07:49:00,072: Unable to initiate TCP/IP socket to 10.0.0.116:44721 (http://10.0.0.116:39812/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,073: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,076: topic[/mavros/state] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,077: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:00,083: topic[/mavlink/from] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,083: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:00,087: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,090: topic[/mavros/battery] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,091: topic[/state_command] removing connection to http://10.0.0.116:43297/
[rospy.internal][INFO] 2017-10-18 07:49:00,092: topic[/state_command] removing connection to http://10.0.0.116:35502/
[rospy.internal][INFO] 2017-10-18 07:49:00,093: topic[/state_command] removing connection to http://10.0.0.116:39812/
[rospy.internal][INFO] 2017-10-18 07:49:00,094: topic[/state_command] removing connection to http://10.0.0.116:41980/
[rospy.internal][ERROR] 2017-10-18 07:49:00,098: Unable to initiate TCP/IP socket to 10.0.0.116:45499 (http://10.0.0.116:38610/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,103: topic[/state_command] removing connection to http://10.0.0.116:38610/
[rospy.topics][ERROR] 2017-10-18 07:49:00,104: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:49:00,106: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:37215/
[rospy.impl.masterslave][INFO] 2017-10-18 07:49:00,107: signal-2
[rospy.internal][WARNING] 2017-10-18 07:49:00,120: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2017-10-18 07:49:00,241: signal_shutdown [atexit]
