[rospy.client][INFO] 2017-10-18 07:32:48,806: init_node, name[/exec], pid[5209]
[xmlrpc][INFO] 2017-10-18 07:32:48,808: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:32:48,809: Started XML-RPC server [http://10.0.0.116:38599/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:32:48,809: _ready: http://10.0.0.116:38599/
[rospy.registration][INFO] 2017-10-18 07:32:48,811: Registering with master node http://10.0.0.116:11311
[rospy.registration][INFO] 2017-10-18 07:32:48,812: Registering publisher topic [/play] type [std_msgs/String] with master
[xmlrpc][INFO] 2017-10-18 07:32:48,822: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:32:48,823: ROS Slave URI: [http://10.0.0.116:38599/]
[rospy.init][INFO] 2017-10-18 07:32:48,924: registered with master
[rospy.rosout][INFO] 2017-10-18 07:32:48,924: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:32:48,933: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:32:48,944: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:32:49,226: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:32:50,048: topic[/play] adding connection to [/chatty], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,029: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,087: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,123: topic[/mavros/state] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,157: topic[/mavros/battery] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,160: topic[/mavlink/from] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,334: topic[/exec_command] adding connection to [http://10.0.0.116:42801/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,342: topic[/exec_command] adding connection to [http://10.0.0.116:33147/], count 1
[rospy.internal][INFO] 2017-10-18 07:32:51,344: topic[/exec_command] adding connection to [http://10.0.0.116:34176/], count 1
[rospy.internal][INFO] 2017-10-18 07:32:51,352: topic[/exec_command] adding connection to [http://10.0.0.116:41071/], count 3
[rosout][INFO] 2017-10-18 07:32:51,359: Exec is starting
[rospy.internal][INFO] 2017-10-18 07:32:51,368: topic[/exec_command] adding connection to [http://10.0.0.116:38599/], count 4
[rospy.internal][INFO] 2017-10-18 07:32:51,379: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,383: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,436: topic[/state_command] adding connection to [/state_driving_to_cone], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,442: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 1
[rospy.internal][INFO] 2017-10-18 07:32:51,448: topic[/state_command] adding connection to [/state_driving_away], count 2
[rospy.internal][INFO] 2017-10-18 07:32:51,454: topic[/state_command] adding connection to [/state_follow_waypoint], count 3
[rospy.internal][INFO] 2017-10-18 07:32:51,482: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:33:02,361: New parameters received
[rosout][INFO] 2017-10-18 07:33:03,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:04,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:05,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:06,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:07,361: New parameters received
[rosout][INFO] 2017-10-18 07:33:08,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:09,361: New parameters received
[rosout][INFO] 2017-10-18 07:33:10,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:11,360: New parameters received
[rosout][INFO] 2017-10-18 07:33:12,360: New parameters received
[rospy.core][INFO] 2017-10-18 07:33:29,907: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:33:30,090: Unable to initiate TCP/IP socket to 10.0.0.116:36384 (http://10.0.0.116:34176/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:33:30,119: Unable to initiate TCP/IP socket to 10.0.0.116:38431 (http://10.0.0.116:33147/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:33:30,126: Unable to initiate TCP/IP socket to 10.0.0.116:38642 (http://10.0.0.116:42801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:33:30,166: Unable to initiate TCP/IP socket to 10.0.0.116:38022 (http://10.0.0.116:41071/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,196: topic[/play] removing connection to /chatty
[rospy.internal][INFO] 2017-10-18 07:33:30,198: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:33:30,200: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:33:30,209: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:33:30,210: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:33:30,213: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:33:30,216: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:33:30,219: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:33:30,221: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:42365/
[rospy.internal][ERROR] 2017-10-18 07:33:30,222: Unable to initiate TCP/IP socket to 10.0.0.116:44772 (http://10.0.0.116:38599/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,222: topic[/exec_command] removing connection to http://10.0.0.116:42801/
[rospy.internal][INFO] 2017-10-18 07:33:30,223: topic[/exec_command] removing connection to http://10.0.0.116:33147/
[rospy.internal][INFO] 2017-10-18 07:33:30,223: topic[/exec_command] removing connection to http://10.0.0.116:34176/
[rospy.internal][INFO] 2017-10-18 07:33:30,224: topic[/exec_command] removing connection to http://10.0.0.116:41071/
[rospy.internal][INFO] 2017-10-18 07:33:30,224: topic[/exec_command] removing connection to http://10.0.0.116:38599/
[rospy.internal][INFO] 2017-10-18 07:33:30,225: topic[/mavros/state] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,226: topic[/mavlink/from] removing connection to http://10.0.0.116:42365/
[rospy.internal][WARNING] 2017-10-18 07:33:30,227: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:33:30,228: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,229: topic[/mavros/battery] removing connection to http://10.0.0.116:42365/
[rospy.internal][WARNING] 2017-10-18 07:33:30,231: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:33:30,232: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:33:30,233: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:42365/
[rospy.impl.masterslave][INFO] 2017-10-18 07:33:30,234: signal-2
[rospy.core][INFO] 2017-10-18 07:33:30,336: signal_shutdown [atexit]
