[rospy.client][INFO] 2017-10-18 07:34:22,161: init_node, name[/state_driving_to_cone], pid[9255]
[xmlrpc][INFO] 2017-10-18 07:34:22,163: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:34:22,164: Started XML-RPC server [http://10.0.0.116:43611/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:34:22,164: _ready: http://10.0.0.116:43611/
[xmlrpc][INFO] 2017-10-18 07:34:22,165: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:34:22,167: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:34:22,169: ROS Slave URI: [http://10.0.0.116:43611/]
[rospy.init][INFO] 2017-10-18 07:34:22,170: registered with master
[rospy.rosout][INFO] 2017-10-18 07:34:22,170: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:34:22,182: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:34:22,206: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:34:22,294: topic[/state_command] adding connection to [http://10.0.0.116:45279/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,296: topic[/state_command] adding connection to [http://10.0.0.116:37700/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,298: topic[/state_command] adding connection to [http://10.0.0.116:41716/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,310: topic[/state_command] adding connection to [http://10.0.0.116:43611/], count 3
[rospy.internal][INFO] 2017-10-18 07:34:22,358: topic[/state_command] adding connection to [/state_driving_to_cone], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,374: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 1
[rospy.internal][INFO] 2017-10-18 07:34:22,382: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:34:22,399: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:34:22,414: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,087: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,167: topic[/mavros/state] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,173: topic[/mavlink/from] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,177: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,179: topic[/mavros/battery] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,422: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,521: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,676: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,701: topic[/state_command] adding connection to [http://10.0.0.116:46044/], count 4
[rospy.core][INFO] 2017-10-18 07:35:11,640: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:35:11,782: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:35:11,783: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:35:11,784: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][ERROR] 2017-10-18 07:35:11,787: Unable to initiate TCP/IP socket to 10.0.0.116:33743 (http://10.0.0.116:43611/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:35:11,789: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:35:11,791: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:35:11,792: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:35:11,793: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:35:11,794: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,795: topic[/mavros/state] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,801: topic[/mavlink/from] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,803: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,806: topic[/mavros/battery] removing connection to http://10.0.0.116:34225/
[rospy.internal][WARNING] 2017-10-18 07:35:11,807: Unknown error initiating TCP/IP socket to 10.0.0.116:49472 (http://10.0.0.116:34225/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:35:11,808: topic[/state_command] removing connection to http://10.0.0.116:45279/
[rospy.internal][INFO] 2017-10-18 07:35:11,810: topic[/state_command] removing connection to http://10.0.0.116:37700/
[rospy.internal][INFO] 2017-10-18 07:35:11,815: topic[/state_command] removing connection to http://10.0.0.116:41716/
[rospy.internal][INFO] 2017-10-18 07:35:11,816: topic[/state_command] removing connection to http://10.0.0.116:43611/
[rospy.internal][INFO] 2017-10-18 07:35:11,817: topic[/state_command] removing connection to http://10.0.0.116:46044/
[rospy.internal][INFO] 2017-10-18 07:35:11,819: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:34225/
[rospy.internal][WARNING] 2017-10-18 07:35:11,820: Unknown error initiating TCP/IP socket to 10.0.0.116:49472 (http://10.0.0.116:34225/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2017-10-18 07:35:11,821: signal-2
[rospy.core][INFO] 2017-10-18 07:35:12,297: signal_shutdown [atexit]
